### ISSUE TITLE
Custom Extractors

### ISSUE THREAD

**Issue by davebally** [MicrosoftBigData/usql#18]
Should custom extractors : ie https://github.com/MicrosoftBigData/usql/tree/master/Examples/DataFormats/Microsoft.Analytics.Samples.Formats

Work in VS with Big Analystics tools or only within Azure ?

Im trying to run and getting "Cannot create assembly 'master.asm' because file 'Microsoft.Analytics.Samples.Formats.dll' could not be read'  .. 

Any clues ?

**Comment by MikeRys** [comment]
You need to have the ADL Tools for visual studios installed. What did you try?

**Comment by davebally** [comment]
ADL is installed (ver 2.0.3000.0 ) and have been able to run the other examples.
The steps i took were :
Load Microsoft.Analytics.Samples.sln and build ( went ok)
Add new USQL project to the solution add example.usql.cs and add reference to Samples project.

When i build that i now get the above error.

I have made some headway and traced using procmon,  and seen that LocalRunHelper.exe is not looking to the expected debug folder for the exe , so copied it to one of the paths it is looking for (the path where the new usqlproj for sampleusql.cs file exists).

Now im getting :
` Severity	Code	Description	Project	File	Line	Suppression State
Error		E_CSC_USER_ROSLYNBINDER: Error when binding C# expression: The type or namespace name 'Xml' does not exist in the namespace 'Microsoft.Analytics.Samples' (are you missing an assembly reference?)
Description:
C# reported that this expression is not valid C#.
Resolution:
Make sure that this expression is a valid C# expression.	TestExample	C:\Projects\usql\Examples\DataFormats\TestExample\example.usql	14	
`

Ive also added `using Microsoft.Analytics.Samples' to example.usql.cs, but same error.

**Comment by omafnan** [comment]
Looks like something YuDong could help with.

Omid

**Comment by yangyud-cn** [comment]
Regarding your first issue, unable to find assembly during registration, we have the following rules in searching for assembly files:
-  Absolute path can be used,   eg:  CREATE ASSEMBLY asm FROM @"c:\project\bin\debug\Microsoft.Analytics.Samples.Formats.dll";  
-  Relative path, currently we will look up in these folders: 
  *  Your local DataRoot  "Visual Studio Menu -> Data Lake -> Options and Settings -> Local Run DataRoot"  (the same as that of ADL where the Default Storage Account located)
  *  Current U-SQL script's source folder or the containing project's folder

Regarding the second issue,  actually the Examples\DataFormats\Microsoft.Analytics.Samples.Formats\Examples\example.usql  contains an error itself.   The 14th line has **"Formats"** missing in name space:
OUTPUT @q TO "foo.xml" USING new Microsoft.Analytics.Samples.**Formats**.Xml.XmlOutputter("foo");

**Comment by davebally** [comment]
Cah, missed the syntax error in the example.usql.

Thanks all, im moving again now :)
